### ISSUE TITLE
Literal value validity.

### ISSUE THREAD

**Issue by afs** [Wimmics/CovidOnTheWeb#1]
Hi there - I ran the data through a data validator (Apache Jena riot - `riot --count --validate FILES`) to check the data. Here is what I found. Commit 0141417.

I can put in some kind of PR though the majority of the report is about the data in the zip files and presumably it is from the conversion code.

1/ `cord19-nekg-example.ttl`

Needs the `dc:` prefix added:
```@prefix dc:     <http://purl.org/dc/elements/1.1/> .```

Error:  line 51
`covidpr:confidence  1^^xsd:decimal;`
should be 
`covidpr:confidence  "1"^^xsd:decimal;`

2/
File: `cord19-nekg-metadata-sha.ttl`
line: 193968
`Bad IRI: <https://doi.org/10.1580/1080-6032(2004)15[231:evdagg]2.0.co;2>`

The characters `[` and `]` aren't legal in the path part of an IRI.

3/ Incorrect datatypes.

Many of the `dct:issued` have the wrong datatype on the date.  They use `xsd:dateTime` when `xsd:date` was meant, e.g. data has `"2018-06-27"^^xsd:dateTime` when `"2018-06-27"^^xsd:date` would be correct.

A few times it is just the year `"2008"^^xsd:dateTime`. These can be `xsd:gYear` or made a valid `xsd:date` by adding `-01-01`.

These are in the zip files. 
File: cord19-nekg-metadata-sha.ttl   (34275 times)
File: cord19-nekg-metadata-pmcid.ttl  (8552 times)

5/ Like 4, cord19-nekg-metadata.ttl also has `xsd:date` and also a similar of `"2020-04-09"^^xsd:gYear`.

**Comment by frmichel** [comment]
Hi Andy,

Thanks a lot for these remarks. I'll take them into account in the next version.
Few questions:
- about Dublin Core, do you think that using namespace dce for elements instead of dc is a problem? I found that it helps distinguish between elements and terms (dct).
-  covidpr:confidence 1^^xsd:decimal; => indeed. Curious as I guess this is what is generated by Jena. I wonder if this is a bug in Jena or a matter of configuration. I'll check this out.
- characters [ and ] in the DOI: Yes there are several issues like this one in the CORD19 dataset. I've already cleaned up a few of them (using '<' and '>' in DOIs) but I had not seen those ones.

Regards,
   Franck.

**Comment by afs** [comment]
Hi Franck,

The prefix can be anything - it's a local choice for the file.  "dc" is the common convention for it and is what is used in the data.

Re: decimal:
If you can say how (which code was called) that is produced by Jena, and which version, I can check but I don't know a route that will print without quotes if it also prints the ^^. The canonical form is `1.0` and does not need the `^^xsd:decimal`. Quite old versions may get this wrong, partly because the canonical rules in XSD changed slightly and partly a bug, but it was some time ago.

Andy

**Comment by frmichel** [comment]
Last commit fixes the following issues.

> 1/ `cord19-nekg-example.ttl`
> Needs the `dc:` prefix added:
> `@prefix dc: <http://purl.org/dc/elements/1.1/> .`

Fixed.

> Error: line 51
> `covidpr:confidence 1^^xsd:decimal;`
> should be
> `covidpr:confidence "1"^^xsd:decimal;`

Fixed by upgrading Jena.

> 2/ File: `cord19-nekg-metadata-sha.ttl`
> line: 193968
> `Bad IRI: <https://doi.org/10.1580/1080-6032(2004)15[231:evdagg]2.0.co;2>`
> The characters `[` and `]` aren't legal in the path part of an IRI.

This will require further filtering in the source dataset. I'll submit another issue specifically for this problem.

> 3/ Incorrect datatypes.
> Many of the `dct:issued` have the wrong datatype on the date. They use `xsd:dateTime` when `xsd:date` was meant, e.g. data has `"2018-06-27"^^xsd:dateTime` when `"2018-06-27"^^xsd:date` would be correct.

Fixed.

> A few times it is just the year `"2008"^^xsd:dateTime`. These can be `xsd:gYear` or made a valid `xsd:date` by adding `-01-01`.
> 5/ Like 4, cord19-nekg-metadata.ttl also has `xsd:date` and also a similar of `"2020-04-09"^^xsd:gYear`.

This is due to the fact that articles are provided with various date formats. That would require filtering the source data to assign either xsd:dataTime or xsd:gYear. For now, only xsd:date is used everywhere.
